### ISSUE TITLE
Testing on Custom Video

### ISSUE THREAD

**Issue by shivinn** [talreiss/FACTOR#3]
How can we test this model on a custom data(video) ? Is it necessary to download the whole FakeAV dataset to run the audio-visual model on a custom deepfake/real video ? I would be really thankful if you could guide me through.

Thanks
Shivin

**Comment by talreiss** [comment]
Hi,

The model can be adapted to any other dataset. All you need to do is modify `audio-visual/preprocess.py` and `audio-visual/inference.py` to point to the location of the new dataset.

Tal

**Comment by kamrul-NSL** [comment]
Thanks @talreiss for this wonderful code-base. I have a question regarding testing on custom video. How can I determine whether a single video is fake or real? The provided **eval.py** gives the AP and AUC score. After using `audio-visual/preprocess.py` and `audio-visual/inference.py`. what is the threshold of the final feature that determine the video is fake/real in the `audio-visual/eval.py`?

**Comment by talreiss** [comment]
Hi,
In order to measure the accuracy of our method we use the both ROC-AUC and PR-AUC metrics, for which no threshold is specified. (See https://en.wikipedia.org/wiki/Receiver_operating_characteristic).
