### ISSUE TITLE
requirements.txt installation error

### ISSUE THREAD

**Issue by AdhithyaS-creator** [talreiss/FACTOR#4]
I was trying to install the stuffs needed by running 'pip install -r requirements.txt' but im getting an error while installing faiss-gpu  
" WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
Discarding https://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz (from https://pypi.org/simple/faiss-gpu/): Requested faiss-cpu from https://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz (from -r requirements.txt (line 14)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'
ERROR: Could not find a version that satisfies the requirement faiss-gpu==1.7.1 (from versions: 1.5.3, 1.6.0, 1.6.1, 1.6.3, 1.6.4, 1.6.4.post2, 1.6.5, 1.7.0, 1.7.1, 1.7.1.post1, 1.7.1.post2)
ERROR: No matching distribution found for faiss-gpu==1.7.1"

This is the error, can you look into it?
![1](https://github.com/talreiss/FACTOR/assets/92566771/b7862486-e12f-4ea5-86fb-945906383a8f)

**Comment by talreiss** [comment]
I just tried installing the requirements file from my end and it worked fine. In any case, I think any other version of the faiss-gpu library will work fine.

Tal
