### ISSUE TITLE
Face_forgery eval performances CelebDF

### ISSUE THREAD

**Issue by battoubattou** [talreiss/FACTOR#5]
Hello,

I tested the face_frogery method with the [**CelebDF**](https://github.com/yuezunli/celeb-deepfakeforensics) Dataset. I used /Celeb_real for identity references and /Celeb_synthesis for the claimed identities. As in the [paper](https://arxiv.org/pdf/2311.01458.pdf) I used 32 frames for each video. Unfortunnatly I cannot found the results I expected to obtain with the paper statistics and have around **50% AUC** (so nothing done). 

Can you give me some infos on what I didn't understand?

**Comment by talreiss** [comment]
Hi,

Have you tested the model per identity? The reference set should only contain real images of a single claimed identity. I would appreciate more information about the experiment that you are trying to evaluate if that's not the case, but it seems like your pre-processing is somehow flawed (whether in terms of the reference set or something else).

Tal

**Comment by battoubattou** [comment]
Yes I preprocess the data I have  (for example to evaluate an attack on Celebrity 0): 

- reference set : /Celeb_real/id0_00001.mp4 (goes trough extract_frames, detect&align and extract_features
- test set: a mix of real videos of Celeb 0 and claimed Celeb 0 (DF) videos
- labels for test set

I then run eval.py on on reference_set features, test_set features and the labels.

I  believe this is how your code is to be used...

**Comment by talreiss** [comment]
Can you tell me what is on the test set? I'd be happy to run it from my end, but I need more specifics.

**Comment by talreiss** [comment]
After running Celeb-DF only on the first identity (id0), I got 99.9% AUROC. Please check your pre-processing (either reference/test sets or feature extraction) as there is a problem there.

**Comment by battoubattou** [comment]
> Can you tell me what is on the test set? I'd be happy to run it from my end, but I need more specifics.

![Capture d’écran du 2023-12-13 09-19-39](https://github.com/talreiss/FACTOR/assets/80097703/fb1b3d8e-5612-49fb-a414-1bc5b96537d5)
This is for example a split between ref and test video for one identity (id5) with one reference and in the test set 8 real videos and 8 fake videos.

Maybe the problem come from my feature extraction, I'll look into it.

**Comment by talreiss** [comment]
Results for the run with ID5 produced 99.9 AUROC. The way you label the images is incorrect. You give a label 1 to the 'real' ones and a label 0 to the 'fake' ones. Our code implementation uses kNN distance to the reference set as a truth score, and lower scores indicate closer to the 'real'. That means 'real' samples should get the label 0, while 'fake' samples should get the label 1.

I hope this helps.
Tal

**Comment by battoubattou** [comment]
Never answered but to keep you updated, everything works fine and weel it was a labelling problem.

**Comment by talreiss** [comment]
Thanks for the update! I'm glad it worked for you.

Tal

**Comment by arhamlet** [comment]
@talreiss , @battoubattou 

So when i create a test set, I get the features of every video inside it in a features.py file. For example, I the test set, I put two videos "id0_0005" and "id2_id0_0005"(folders containing frames after preprocessing) . Now i get features .npy in both these folders individually. How do i run the eval.py on my test set. Also, I placed one folder in reference set "id0_0000" that contains the features.py file in it. What should be the format of the label file as well.

Here is my directory

reference path: test_data/celeb-reat/id0_0000
test path: test_data/celeb-synthesis/id0_0005 and test_data/celeb-synthesis/id2_id0_0005
labels path: Don't know how to create the label file or its format
