### ISSUE TITLE
How to build the label.npy file？

### ISSUE THREAD

**Issue by jushe** [talreiss/FACTOR#6]
I want to use face-forgery and test two video , one is the real and other is fake.
So I use FaceX-Zoo to get the .npy files. But I don't know how to  build the label.npy. 
Should I use an array like [1, 2.....] and convert it to nparry and save as the .npy ?

My dataset like:
```
/content/output_data/
├── fakeobama
│   ├── frame0.jpg
│   ├── frame100.jpg
│   ├── frame101.jpg
│   ├── frame102.jpg
      └── frame9.jpg
└── realobama
    ├── frame0.jpg
    ├── frame100.jpg
    ├── frame101.jpg
    └── frame9.jpg
```

**Comment by talreiss** [comment]
You should have a numpy array of size (9,) with the first five samples (fake obama) getting the label 1, and the last four samples (real obama) getting the label 0. 

Hope this helps.
Tal
